services:
  - type: web
    name: crm-autoescuela
    env: python
    plan: free
    rootDir: crm_autoescuela
    buildCommand: |
      pip install --upgrade pip
      pip install -r ../requirements.txt
      python manage.py migrate
      python manage.py collectstatic --no-input
    startCommand: gunicorn crm_autoescuela.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.4"
