services:
  - type: web
    name: crm-autoescuela
    env: python
    plan: free
    rootDir: .
    buildCommand: ./build.sh
    startCommand: cd crm_autoescuela && gunicorn crm_autoescuela.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.4"
